/** OraSage Entertainment-Only 声明文案（PRD §8.1 / R1） */

export type DisclaimerVariant = 'standard' | 'full' | 'product' | 'transaction' | 'compact';

export type DisclaimerLocale = 'zh' | 'en';

type CopyBlock = { title: string; body: string[]; figureNote?: string };

const COMPACT: Record<DisclaimerLocale, CopyBlock> = {
  zh: {
    title: '🎭 娱乐与自我探索 · Entertainment',
    body: ['不构成医疗、财务、法律或人生决策建议。'],
  },
  en: {
    title: '🎭 Entertainment & self-exploration',
    body: ['Not medical, financial, legal or life-decision advice.'],
  },
};

const STANDARD: Record<DisclaimerLocale, CopyBlock> = {
  zh: {
    title: '🎭 娱乐用途声明 · Entertainment-Only Notice',
    body: [
      'OraSage 的八字、紫微斗数与塔罗解读，以及我们的水晶内容，均为文化娱乐与自我探索工具，不构成医疗、财务、法律或人生决策建议。结果由算法基于公开历法模型生成，仅供您参考。',
    ],
  },
  en: {
    title: '🎭 Entertainment-Only Notice',
    body: [
      "OraSage's BaZi, Zi Wei Dou Shu, and Tarot readings, together with our crystal content, are cultural-entertainment and self-exploration tools. They do not constitute medical, financial, legal, or life-decision advice. Results are generated by algorithm from public calendar models and are provided for your reference only.",
    ],
  },
};

const FULL: Record<DisclaimerLocale, CopyBlock> = {
  zh: {
    title: '🎭 娱乐与自我探索工具 · Entertainment-Only',
    body: [
      '本页内容由 OraSage 算法依据您（或公开人物）输入的出生信息自动生成，仅供娱乐与文化参考。',
      '• 非医疗建议：不替代专业诊断或治疗；如有健康困扰请咨询持证医师。',
      '• 非财务 / 投资建议：不预测收益，不指导任何交易或投资。',
      '• 非命运定论：传统命理提供的是一种文化视角的自我觉察，而非既定结局。结构可供对照，选择仍由你自己做出。',
      '数据来源：基于中国传统历法与命理文献的公开算法模型；结果存在传统流派差异，并非绝对真理。',
    ],
    figureNote:
      '• 本页人物解读为基于公开出生资料的娱乐性文化演绎，既非真实命盘结论，也不代表本人观点。',
  },
  en: {
    title: '🎭 Entertainment & Self-Exploration Tool',
    body: [
      "This page is generated automatically by OraSage's algorithm from the birth details you (or a public figure) provide. It is for entertainment and cultural reference only.",
      '• Not medical advice — does not replace professional diagnosis or treatment. Consult a licensed physician for health concerns.',
      '• Not financial or investment advice — does not predict returns or direct any trade or investment.',
      '• Not a fixed destiny — traditional metaphysics offers a cultural lens for self-awareness, not a predetermined outcome. Structure is for reflection; choices remain yours.',
      'Data source: Public algorithmic models based on traditional Chinese calendar and metaphysics literature. Results vary across traditions and are not absolute truth.',
    ],
    figureNote:
      "• This figure's profile is an entertainment interpretation based on publicly available birth data — not a verified chart, and not an endorsement of the individual.",
  },
};

const PRODUCT: Record<DisclaimerLocale, CopyBlock> = {
  zh: {
    title: '💎 文化符号说明',
    body: [
      '水晶饰品是传统文化中的象征物与心理锚点。本页描述为文化意象与情感寄托，不构成任何疗效、健康或运势承诺。佩戴体验因人而异。',
    ],
  },
  en: {
    title: '💎 Cultural Symbol Note',
    body: [
      'Crystals are traditional-cultural symbols and psychological anchors. Descriptions here reflect cultural imagery and intention-setting — not any promise of therapeutic, health, or fortune effects. Experience varies by individual.',
    ],
  },
};

const TRANSACTION: Record<DisclaimerLocale, CopyBlock> = {
  zh: {
    title: '🧾 交易提示',
    body: [
      '您购买的是文化饰品与娱乐内容服务。本订单不构成医疗、财务或人生决策建议，且不保证任何具体结果。退换依《退换政策》办理。',
    ],
  },
  en: {
    title: '🧾 Transaction Note',
    body: [
      'You are purchasing cultural goods and entertainment-content services. This order is not medical, financial, or life-decision advice and guarantees no specific outcome. Returns are handled per our Return Policy. · For entertainment purposes only. No outcome guaranteed.',
    ],
  },
};

const BY_VARIANT: Record<DisclaimerVariant, Record<DisclaimerLocale, CopyBlock>> = {
  compact: COMPACT,
  standard: STANDARD,
  full: FULL,
  product: PRODUCT,
  transaction: TRANSACTION,
};

/** Map site locales (zh-CN / en / pt-BR …) → disclaimer language bucket */
export function disclaimerLocale(siteLocale?: string | null): DisclaimerLocale {
  const loc = (siteLocale || 'en').toLowerCase();
  if (loc === 'zh' || loc.startsWith('zh-')) return 'zh';
  return 'en';
}

export function getDisclaimerCopy(
  variant: DisclaimerVariant,
  siteLocale?: string | null,
  figureNote = false,
): { title: string; lines: string[] } {
  const lang = disclaimerLocale(siteLocale);
  const block = BY_VARIANT[variant][lang];
  const lines = [...block.body];
  if (figureNote && block.figureNote) lines.push(block.figureNote);
  return { title: block.title, lines };
}

/** Plain-text for email / PDF */
export function getDisclaimerPlainText(
  variant: DisclaimerVariant,
  siteLocale?: string | null,
  figureNote = false,
): string {
  const { title, lines } = getDisclaimerCopy(variant, siteLocale, figureNote);
  return [title, ...lines].join('\n');
}
