import type { Config } from 'payload';

/** Payload 后台界面与通用错误提示的中文化覆盖 */
export const cmsZhTranslations: NonNullable<Config['i18n']>['translations'] = {
  zh: {
    general: {
      dashboard: '工作台',
      save: '保存',
      saving: '保存中…',
      create: '新建',
      edit: '编辑',
      delete: '删除',
      cancel: '取消',
      confirm: '确认',
      searchBy: '搜索{{label}}',
      noResults: '未找到结果',
      loading: '加载中…',
      error: '出错了',
      success: '操作成功',
      required: '必填',
      upload: '上传',
      select: '选择',
      clear: '清除',
      close: '关闭',
      back: '返回',
      next: '下一步',
      previous: '上一步',
      submit: '提交',
      logout: '退出登录',
      login: '登录',
      email: '邮箱',
      password: '密码',
      confirmPassword: '确认密码',
      welcome: '欢迎',
      collections: '内容集合',
      globals: '全站配置',
    },
    error: {
      required: '此字段为必填项',
      notAllowed: '不允许此操作',
      userEmail: '请输入有效的邮箱地址',
      userPassword: '密码至少需要 {{minLength}} 个字符',
      userUsername: '请输入用户名',
      documentNotFound: '未找到对应内容',
      notFound: '未找到请求的资源',
      unknown: '发生未知错误，请稍后重试',
    },
    validation: {
      required: '请填写此字段',
      emailAddress: '请输入有效的邮箱地址',
      enterNumber: '请输入数字',
      minimumValue: '最小值为 {{min}}',
      maximumValue: '最大值为 {{max}}',
      longerThanMin: '长度不能少于 {{minLength}} 个字符',
      shorterThanMax: '长度不能超过 {{maxLength}} 个字符',
      username: '用户名格式不正确',
      password: '密码不符合要求',
    },
    fields: {
      addNew: '添加',
      addNewLabel: '新建{{label}}',
      chooseFromExisting: '从已有内容选择',
      custom: '自定义',
      uploadNewLabel: '上传新{{label}}',
    },
    version: {
      aboutToPublish: '即将发布此版本',
      aboutToUnpublish: '即将取消发布',
      draft: '草稿',
      published: '已发布',
    },
  },
};
