#!/usr/bin/env node
/**
 * Sync OraSage design tokens from the runtime authority into @orasage/tokens.
 *
 * Authority: shared/design-tokens/orasage-tokens.css
 * Package copy: packages/tokens/src/orasage-tokens.css
 *
 * Usage:
 *   node scripts/tokens/sync-tokens.mjs          # write package copy
 *   node scripts/tokens/sync-tokens.mjs check    # exit 1 if out of sync
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');
const SOURCE = path.join(ROOT, 'shared/design-tokens/orasage-tokens.css');
const DEST = path.join(ROOT, 'packages/tokens/src/orasage-tokens.css');

const GENERATED_BANNER = `/**
 * @orasage/tokens package copy — DO NOT EDIT
 * Generated by \`npm run tokens:sync\`
 * Authority: shared/design-tokens/orasage-tokens.css
 */

`;

function readAuthority() {
  if (!fs.existsSync(SOURCE)) {
    console.error(`[tokens] authority file missing: ${SOURCE}`);
    process.exit(1);
  }
  return fs.readFileSync(SOURCE, 'utf8');
}

function buildPackageCopy(source) {
  return `${GENERATED_BANNER}${source.endsWith('\n') ? source : `${source}\n`}`;
}

function stripGeneratedBanner(content) {
  if (!content.startsWith('/**')) return content;
  const end = content.indexOf('*/');
  if (end === -1) return content;
  return content.slice(end + 2).replace(/^\s*\n/, '');
}

export function syncTokens({ quiet = false } = {}) {
  const source = readAuthority();
  const next = buildPackageCopy(source);
  fs.mkdirSync(path.dirname(DEST), { recursive: true });
  fs.writeFileSync(DEST, next, 'utf8');
  if (!quiet) {
    console.log(`[tokens] synced ${path.relative(ROOT, SOURCE)} → ${path.relative(ROOT, DEST)}`);
  }
  return next;
}

export function checkTokens() {
  const source = readAuthority();
  const expected = buildPackageCopy(source);

  if (!fs.existsSync(DEST)) {
    console.error(`[tokens] package copy missing: ${DEST}`);
    console.error('[tokens] run: npm run tokens:sync');
    process.exit(1);
  }

  const actual = fs.readFileSync(DEST, 'utf8');
  if (actual === expected) {
    console.log('[tokens] check ok — package copy matches authority');
    return;
  }

  const actualBody = stripGeneratedBanner(actual);
  if (actualBody === source) {
    console.error('[tokens] package copy body matches but generated banner differs');
    console.error('[tokens] run: npm run tokens:sync');
    process.exit(1);
  }

  console.error('[tokens] package copy is out of sync with authority');
  console.error(`  authority: ${path.relative(ROOT, SOURCE)}`);
  console.error(`  package:   ${path.relative(ROOT, DEST)}`);
  console.error('[tokens] run: npm run tokens:sync');
  process.exit(1);
}

const mode = process.argv[2];
if (mode === 'check') {
  checkTokens();
} else if (mode === 'sync' || !mode) {
  syncTokens();
} else {
  console.error(`[tokens] unknown mode: ${mode} (use sync | check)`);
  process.exit(1);
}
