/**
 * Seed data for CMS faiths + sanctuaries (synced with tarot/src/lib/faiths/*)
 */
import type { WorshipFacingMode } from './tarot-facing';

type SeedFaith = {
  code: string;
  nameZh: string;
  nameEn: string;
  emoji: string;
  rank: number;
  adherentsM: number;
  worshipFacing?: WorshipFacingMode;
};

export const SEED_FAITHS: SeedFaith[] = [
  { code: 'christianity', nameZh: '基督教', nameEn: 'Christianity', emoji: '✝️', rank: 1, adherentsM: 2380 },
  { code: 'islam', nameZh: '伊斯兰教', nameEn: 'Islam', emoji: '☪️', rank: 2, adherentsM: 1910, worshipFacing: 'qibla' },
  { code: 'hinduism', nameZh: '印度教', nameEn: 'Hinduism', emoji: '🕉️', rank: 3, adherentsM: 1160, worshipFacing: 'east' },
  { code: 'buddhism', nameZh: '佛教', nameEn: 'Buddhism', emoji: '☸️', rank: 4, adherentsM: 507, worshipFacing: 'east' },
  { code: 'chinese_folk', nameZh: '中国民间信仰', nameEn: 'Chinese Folk Religion', emoji: '🏮', rank: 5, adherentsM: 394, worshipFacing: 'east' },
  { code: 'african_traditional', nameZh: '非洲传统宗教', nameEn: 'African Traditional Religions', emoji: '🌍', rank: 6, adherentsM: 100 },
  { code: 'sikhism', nameZh: '锡克教', nameEn: 'Sikhism', emoji: '☬', rank: 7, adherentsM: 26, worshipFacing: 'east' },
  { code: 'spiritism', nameZh: '灵性主义', nameEn: 'Spiritism', emoji: '👁️', rank: 8, adherentsM: 15 },
  { code: 'judaism', nameZh: '犹太教', nameEn: 'Judaism', emoji: '✡️', rank: 9, adherentsM: 15, worshipFacing: 'jerusalem' },
  { code: 'taoism', nameZh: '道教', nameEn: 'Taoism', emoji: '☯️', rank: 10, adherentsM: 12, worshipFacing: 'east' },
  { code: 'shinto', nameZh: '神道教', nameEn: 'Shinto', emoji: '⛩️', rank: 11, adherentsM: 4, worshipFacing: 'east' },
  { code: 'bahai', nameZh: '巴哈伊教', nameEn: "Bahá'í Faith", emoji: '⭐', rank: 12, adherentsM: 8 },
  { code: 'jainism', nameZh: '耆那教', nameEn: 'Jainism', emoji: '🙏', rank: 13, adherentsM: 5 },
  { code: 'zoroastrianism', nameZh: '琐罗亚斯德教', nameEn: 'Zoroastrianism', emoji: '🔥', rank: 14, adherentsM: 0.2 },
  { code: 'cao_dai', nameZh: '高台教', nameEn: 'Caodaism', emoji: '🌸', rank: 15, adherentsM: 4 },
  { code: 'confucianism', nameZh: '儒教', nameEn: 'Confucianism', emoji: '📜', rank: 16, adherentsM: 6, worshipFacing: 'east' },
  { code: 'korean_shamanism', nameZh: '韩国巫教', nameEn: 'Korean Shamanism', emoji: '🎭', rank: 17, adherentsM: 5 },
  { code: 'indigenous', nameZh: '原住民信仰', nameEn: 'Indigenous Religions', emoji: '🦅', rank: 18, adherentsM: 300 },
  { code: 'afro_brazilian', nameZh: '非裔巴西宗教', nameEn: 'Afro-Brazilian Religions', emoji: '🌊', rank: 19, adherentsM: 2 },
  { code: 'tenrikyo', nameZh: '天理教', nameEn: 'Tenrikyo', emoji: '🌅', rank: 20, adherentsM: 2 },
  { code: 'none', nameZh: '无特定信仰', nameEn: 'No Specific Faith', emoji: '🌿', rank: 98, adherentsM: 0 },
  { code: 'other', nameZh: '其他', nameEn: 'Other', emoji: '⋯', rank: 99, adherentsM: 0 },
];

export type SeedSanctuary = {
  code: string;
  nameZh: string;
  nameEn: string;
  /** Portuguese display name (pt-BR UI). Falls back to nameEn when omitted. */
  namePt?: string;
  /** Spanish display name. Falls back to nameEn when omitted. */
  nameEs?: string;
  faithCodes: string[];
  tradition: 'latin' | 'seasia' | 'global';
  region: string;
  domains: string[];
  color: string;
  gradient: string;
  imageUrl: string;
  sortOrder: number;
  blessingText?: string;
};

export const SEED_SANCTUARIES: SeedSanctuary[] = [
  {
    code: 'aparecida',
    nameZh: '阿帕雷西达圣母',
    nameEn: 'Nossa Senhora Aparecida',
    namePt: 'Nossa Senhora Aparecida',
    nameEs: 'Nuestra Señora Aparecida',
    faithCodes: ['christianity'],
    tradition: 'latin',
    region: 'Brazil',
    domains: ['奇迹', '母爱', '庇护'],
    color: '#1A3A5C',
    gradient: 'linear-gradient(160deg, #1A3A5C, #2A4A6C)',
    imageUrl: '/gods/aparecida.webp',
    sortOrder: 10,
  },
  {
    code: 'guadalupe',
    nameZh: '瓜达卢佩圣母',
    nameEn: 'Virgen de Guadalupe',
    namePt: 'Virgem de Guadalupe',
    nameEs: 'Virgen de Guadalupe',
    faithCodes: ['christianity'],
    tradition: 'latin',
    region: 'Mexico/Central America',
    domains: ['慈悲', '家庭', '底层守护'],
    color: '#8B2E3A',
    gradient: 'linear-gradient(160deg, #5B1A25, #8B2E3A)',
    imageUrl: '/gods/guadalupe.webp',
    sortOrder: 20,
  },
  {
    code: 'lujan',
    nameZh: '卢汉圣母',
    nameEn: 'Our Lady of Luján',
    namePt: 'Nossa Senhora de Luján',
    nameEs: 'Nuestra Señora de Luján',
    faithCodes: ['christianity'],
    tradition: 'latin',
    region: 'Argentina',
    domains: ['旅人保护', '平安', '方向'],
    color: '#5B8FA6',
    gradient: 'linear-gradient(160deg, #3A6070, #5B8FA6)',
    imageUrl: '/gods/lujan.webp',
    sortOrder: 30,
  },
  {
    code: 'santonino',
    nameZh: '圣婴耶稣',
    nameEn: 'Santo Niño de Cebú',
    namePt: 'Santo Niño de Cebú',
    nameEs: 'Santo Niño de Cebú',
    faithCodes: ['christianity'],
    tradition: 'latin',
    region: 'Philippines',
    domains: ['奇迹', '希望', '孩子'],
    color: '#8B2020',
    gradient: 'linear-gradient(160deg, #5B1010, #8B2020)',
    imageUrl: '/gods/santo-nino.webp',
    sortOrder: 40,
  },
  {
    code: 'guanyin',
    nameZh: '观音',
    nameEn: 'Guan Yin',
    namePt: 'Guan Yin',
    nameEs: 'Guan Yin',
    faithCodes: ['buddhism', 'chinese_folk', 'taoism'],
    tradition: 'seasia',
    region: 'Chinese Diaspora / Thailand',
    domains: ['慈悲', '救苦', '子嗣'],
    color: '#D4C8C0',
    gradient: 'linear-gradient(160deg, #B8ACA4, #F0E8E0)',
    imageUrl: '/gods/guanyin.webp',
    sortOrder: 50,
    blessingText: '慈悲之光已照见你的心愿，今日向前走一步。',
  },
  {
    code: 'brahma',
    nameZh: '四面佛',
    nameEn: 'Brahma (Erawan)',
    namePt: 'Brahma (Erawan)',
    nameEs: 'Brahma (Erawan)',
    faithCodes: ['hinduism', 'buddhism'],
    tradition: 'seasia',
    region: 'Thailand',
    domains: ['全能护佑', '事业', '财运'],
    color: '#C9954A',
    gradient: 'linear-gradient(160deg, #A67A38, #D4A853)',
    imageUrl: '/gods/brahma.webp',
    sortOrder: 60,
  },
  {
    code: 'ganesha',
    nameZh: '象神',
    nameEn: 'Ganesha',
    namePt: 'Ganesha',
    nameEs: 'Ganesha',
    faithCodes: ['hinduism'],
    tradition: 'seasia',
    region: 'India / Thailand',
    domains: ['除障', '智慧', '学业'],
    color: '#D4782A',
    gradient: 'linear-gradient(160deg, #B06020, #E89040)',
    imageUrl: '/gods/ganesha.webp',
    sortOrder: 70,
  },
  {
    code: 'mazu',
    nameZh: '妈祖',
    nameEn: 'Mazu',
    namePt: 'Mazu',
    nameEs: 'Mazu',
    faithCodes: ['chinese_folk', 'taoism'],
    tradition: 'seasia',
    region: 'Chinese Diaspora',
    domains: ['出海平安', '女性力量'],
    color: '#8B2020',
    gradient: 'linear-gradient(160deg, #5B1010, #A03030)',
    imageUrl: '/gods/mazu.webp',
    sortOrder: 80,
  },
  // ── 主流宗教守护神扩展（每信仰至少一位）────────────────────────
  {
    code: 'fatima',
    nameZh: '法蒂玛',
    nameEn: 'Fatima Zahra',
    faithCodes: ['islam'],
    tradition: 'global',
    region: 'Middle East / Global',
    domains: ['慈悲', '家庭', '守护'],
    color: '#1B5E4A',
    gradient: 'linear-gradient(160deg, #0D3B2E, #1B5E4A)',
    imageUrl: '/gods/fatima.webp',
    sortOrder: 90,
    blessingText: '愿平安与坚韧与你同行，今日心怀善念。',
  },
  {
    code: 'shiva',
    nameZh: '湿婆',
    nameEn: 'Shiva',
    faithCodes: ['hinduism'],
    tradition: 'global',
    region: 'India',
    domains: ['转化', '护佑', '内在力量'],
    color: '#4A5568',
    gradient: 'linear-gradient(160deg, #2D3748, #4A5568)',
    imageUrl: '/gods/shiva.webp',
    sortOrder: 100,
    blessingText: '在变化中保持清明，你的路正在展开。',
  },
  {
    code: 'lakshmi',
    nameZh: '拉克什米',
    nameEn: 'Lakshmi',
    faithCodes: ['hinduism'],
    tradition: 'global',
    region: 'India / Southeast Asia',
    domains: ['丰饶', '吉祥', '家宅'],
    color: '#C9954A',
    gradient: 'linear-gradient(160deg, #A67A38, #E8C878)',
    imageUrl: '/gods/lakshmi.webp',
    sortOrder: 110,
  },
  {
    code: 'shakyamuni',
    nameZh: '释迦牟尼',
    nameEn: 'Shakyamuni Buddha',
    faithCodes: ['buddhism'],
    tradition: 'global',
    region: 'South Asia / Global',
    domains: ['觉悟', '平静', '智慧'],
    color: '#B8943F',
    gradient: 'linear-gradient(160deg, #8B7030, #D4B86A)',
    imageUrl: '/gods/shakyamuni.webp',
    sortOrder: 120,
    blessingText: '安住当下，心若止水，福慧渐增。',
  },
  {
    code: 'ksitigarbha',
    nameZh: '地藏菩萨',
    nameEn: 'Ksitigarbha',
    faithCodes: ['buddhism', 'chinese_folk'],
    tradition: 'seasia',
    region: 'East Asia',
    domains: ['救度', '孝道', '誓愿'],
    color: '#6B5344',
    gradient: 'linear-gradient(160deg, #4A3828, #8B7058)',
    imageUrl: '/gods/ksitigarbha.webp',
    sortOrder: 130,
  },
  {
    code: 'guan_yu',
    nameZh: '关公',
    nameEn: 'Guan Yu',
    faithCodes: ['chinese_folk', 'confucianism'],
    tradition: 'seasia',
    region: 'China / Chinese Diaspora',
    domains: ['忠义', '护佑', '财运'],
    color: '#8B2020',
    gradient: 'linear-gradient(160deg, #5B1010, #B03030)',
    imageUrl: '/gods/guan_yu.webp',
    sortOrder: 140,
  },
  {
    code: 'jade_emperor',
    nameZh: '玉皇大帝',
    nameEn: 'Jade Emperor',
    faithCodes: ['taoism', 'chinese_folk'],
    tradition: 'seasia',
    region: 'China',
    domains: ['天界护佑', '秩序', '福泽'],
    color: '#D4AF37',
    gradient: 'linear-gradient(160deg, #A68B28, #F0D878)',
    imageUrl: '/gods/jade_emperor.webp',
    sortOrder: 150,
  },
  {
    code: 'ogun',
    nameZh: '奥贡',
    nameEn: 'Ogun',
    faithCodes: ['african_traditional', 'afro_brazilian'],
    tradition: 'global',
    region: 'West Africa / Americas',
    domains: ['力量', '道路', '工匠'],
    color: '#2D5016',
    gradient: 'linear-gradient(160deg, #1A3009, #3D6B22)',
    imageUrl: '/gods/ogun.webp',
    sortOrder: 160,
  },
  {
    code: 'guru_nanak',
    nameZh: '古鲁·那纳克',
    nameEn: 'Guru Nanak',
    faithCodes: ['sikhism'],
    tradition: 'global',
    region: 'Punjab / Global',
    domains: ['平等', '真理', '指引'],
    color: '#F59E0B',
    gradient: 'linear-gradient(160deg, #D97706, #FCD34D)',
    imageUrl: '/gods/guru_nanak.webp',
    sortOrder: 170,
    blessingText: '在真理与仁爱的光中，今日亦被护佑。',
  },
  {
    code: 'allan_kardec',
    nameZh: '阿兰·卡里德',
    nameEn: 'Allan Kardec',
    namePt: 'Allan Kardec',
    nameEs: 'Allan Kardec',
    faithCodes: ['spiritism'],
    tradition: 'latin',
    region: 'Brazil / Global',
    domains: ['灵性指引', '疗愈', '沟通'],
    color: '#6366F1',
    gradient: 'linear-gradient(160deg, #4338CA, #818CF8)',
    imageUrl: '/gods/allan_kardec.webp',
    sortOrder: 180,
  },
  {
    code: 'elijah',
    nameZh: '以利亚',
    nameEn: 'Elijah',
    faithCodes: ['judaism'],
    tradition: 'global',
    region: 'Middle East / Global',
    domains: ['先知', '护佑', '希望'],
    color: '#1E3A5F',
    gradient: 'linear-gradient(160deg, #0F2744, #2E5A8C)',
    imageUrl: '/gods/elijah.webp',
    sortOrder: 190,
    blessingText: '愿你在风雨中仍见火光，心有所依。',
  },
  {
    code: 'amaterasu',
    nameZh: '天照大神',
    nameEn: 'Amaterasu',
    faithCodes: ['shinto'],
    tradition: 'global',
    region: 'Japan',
    domains: ['光明', '秩序', '皇室护佑'],
    color: '#DC2626',
    gradient: 'linear-gradient(160deg, #991B1B, #F87171)',
    imageUrl: '/gods/amaterasu.webp',
    sortOrder: 200,
  },
  {
    code: 'bahaullah',
    nameZh: '巴哈欧拉',
    nameEn: "Bahá'u'lláh",
    faithCodes: ['bahai'],
    tradition: 'global',
    region: 'Persia / Global',
    domains: ['人类一体', '和平', '启示'],
    color: '#7C3AED',
    gradient: 'linear-gradient(160deg, #5B21B6, #A78BFA)',
    imageUrl: '/gods/bahaullah.webp',
    sortOrder: 210,
  },
  {
    code: 'mahavira',
    nameZh: '大雄',
    nameEn: 'Mahavira',
    faithCodes: ['jainism'],
    tradition: 'global',
    region: 'India',
    domains: ['非暴', '解脱', '自律'],
    color: '#F5F5DC',
    gradient: 'linear-gradient(160deg, #E8E4D0, #FFFEF5)',
    imageUrl: '/gods/mahavira.webp',
    sortOrder: 220,
  },
  {
    code: 'ahura_mazda',
    nameZh: '阿胡拉·马兹达',
    nameEn: 'Ahura Mazda',
    faithCodes: ['zoroastrianism'],
    tradition: 'global',
    region: 'Persia / Iran',
    domains: ['光明', '智慧', '正义'],
    color: '#FBBF24',
    gradient: 'linear-gradient(160deg, #D97706, #FDE68A)',
    imageUrl: '/gods/ahura_mazda.webp',
    sortOrder: 230,
  },
  {
    code: 'confucius',
    nameZh: '孔子',
    nameEn: 'Confucius',
    faithCodes: ['confucianism'],
    tradition: 'seasia',
    region: 'China / East Asia',
    domains: ['仁义', '学问', '修身'],
    color: '#78350F',
    gradient: 'linear-gradient(160deg, #451A03, #A16207)',
    imageUrl: '/gods/confucius.webp',
    sortOrder: 240,
    blessingText: '学而时习之，今日宜修身正心。',
  },
  {
    code: 'dangun',
    nameZh: '檀君王',
    nameEn: 'Dangun',
    faithCodes: ['korean_shamanism'],
    tradition: 'global',
    region: 'Korea',
    domains: ['开国', '山神', '护国'],
    color: '#059669',
    gradient: 'linear-gradient(160deg, #047857, #34D399)',
    imageUrl: '/gods/dangun.webp',
    sortOrder: 250,
  },
  {
    code: 'pachamama',
    nameZh: '帕查 Mama',
    nameEn: 'Pachamama',
    namePt: 'Pachamama',
    nameEs: 'Pachamama',
    faithCodes: ['indigenous'],
    tradition: 'latin',
    region: 'Andes / Americas',
    domains: ['大地', '丰饶', '生命'],
    color: '#65A30D',
    gradient: 'linear-gradient(160deg, #3F6212, #84CC16)',
    imageUrl: '/gods/pachamama.webp',
    sortOrder: 260,
  },
  {
    code: 'iemanja',
    nameZh: '伊曼雅',
    nameEn: 'Yemanjá',
    namePt: 'Iemanjá',
    nameEs: 'Yemayá',
    faithCodes: ['afro_brazilian', 'spiritism'],
    tradition: 'latin',
    region: 'Brazil / Caribbean',
    domains: ['海洋', '母性', '疗愈'],
    color: '#0EA5E9',
    gradient: 'linear-gradient(160deg, #0369A1, #38BDF8)',
    imageUrl: '/gods/iemanja.webp',
    sortOrder: 270,
    blessingText: '如海般包容，愿你的心愿被温柔承接。',
  },
  {
    code: 'oyasama',
    nameZh: '天理王母',
    nameEn: 'Oyasama',
    faithCodes: ['tenrikyo'],
    tradition: 'global',
    region: 'Japan',
    domains: ['天理', '救苦', '家庭'],
    color: '#EC4899',
    gradient: 'linear-gradient(160deg, #BE185D, #F9A8D4)',
    imageUrl: '/gods/oyasama.webp',
    sortOrder: 280,
  },
  {
    code: 'cao_dai_mother',
    nameZh: '母道',
    nameEn: 'Cao Dai Mother Goddess',
    faithCodes: ['cao_dai'],
    tradition: 'seasia',
    region: 'Vietnam',
    domains: ['慈悲', '合一', '救度'],
    color: '#A855F7',
    gradient: 'linear-gradient(160deg, #7E22CE, #D8B4FE)',
    imageUrl: '/gods/cao_dai_mother.webp',
    sortOrder: 290,
  },
];
